

-- -----------------------------------------------------
-- SCHEMA RSP_SCHEMA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- SCHEMA RSP_SCHEMA
-- -----------------------------------------------------
-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.OPEN_GRAPH
-- -----------------------------------------------------


CREATE TABLE RSP_IMAGE (
  ID_IMAGE INTEGER PRIMARY KEY,
  IMAGE BYTEA NOT NULL,
  TYPE VARCHAR(20) NOT NULL DEFAULT 'JPEG',
  DATE TIMESTAMP NOT NULL,
  ID_POST INTEGER NULL);





CREATE TABLE  RSP_USUARIO(
  ID_USUARIO INTEGER PRIMARY KEY,
  LOGIN VARCHAR(100) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  SENHA CHAR(32) NULL DEFAULT NULL,
  ID_PROFILE_IMAGE INTEGER NULL  ,
  LDAP BOOLEAN NOT NULL DEFAULT FALSE);


CREATE TABLE RSP_OPEN_GRAPH (
  ID_OPEN_GRAPH INTEGER PRIMARY KEY,
  URL VARCHAR(200) NOT NULL,
  TITLE TEXT NOT NULL,
  DESCRIPTION TEXT NULL,
  IMAGE VARCHAR(200) NULL);


-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.POST
-- -----------------------------------------------------
CREATE TABLE RSP_POST (
  ID_POST INTEGER PRIMARY KEY,
  TEXTO TEXT NOT NULL,
  DATA TIMESTAMP NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  ID_POST_PARENT INTEGER NULL,
  ID_OPEN_GRAPH INTEGER NULL);



-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.IMAGE
-- -----------------------------------------------------



-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.USUARIO
-- -----------------------------------------------------



-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.USUARIO_LOGIN
-- -----------------------------------------------------
CREATE TABLE RSP_USUARIO_LOGIN (
  TOKEN CHAR(36) NOT NULL,
  DATA_LOGIN TIMESTAMP NOT NULL,
  DATA_LOGOUT TIMESTAMP NULL DEFAULT NULL,
  ID_USUARIO INTEGER NOT NULL);



-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.LIST
-- -----------------------------------------------------
CREATE TABLE RSP_LIST (
  ID_LIST INTEGER PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL UNIQUE);


-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.FOLLOW
-- -----------------------------------------------------
CREATE TABLE RSP_FOLLOW (
  ID_FOLLOW INTEGER PRIMARY KEY,
  ID_FOLLOWER INTEGER NOT NULL,
  ID_FOLLOWED INTEGER NULL,
  ID_LIST_FOLLOWED INTEGER NULL);

-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.PROFILE_FIELD
-- -----------------------------------------------------
CREATE TABLE RSP_PROFILE_FIELD (
  ID_PROFILE_FIELD INTEGER PRIMARY KEY,
  LABEL VARCHAR(45) NOT NULL,
  INDEX INTEGER NOT NULL,
  MULTILINE BOOLEAN NULL);



-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.PROFILE_FIELD_VALUE
-- -----------------------------------------------------
CREATE TABLE RSP_PROFILE_FIELD_VALUE (
  ID_USUARIO INTEGER NOT NULL,
  ID_PROFILE_FIELD INTEGER NOT NULL,
  VALUE TEXT NOT NULL,
  PRIMARY KEY(ID_USUARIO,ID_PROFILE_FIELD));



ALTER TABLE RSP_IMAGE         ADD CONSTRAINT C_RSP_IMAGE_FK_POST            FOREIGN KEY (ID_POST)           REFERENCES RSP_POST(ID_POST);
ALTER TABLE RSP_USUARIO       ADD CONSTRAINT C_RSP_USUARIO_FK_P_IMAGE       FOREIGN KEY (ID_PROFILE_IMAGE)  REFERENCES RSP_IMAGE (ID_IMAGE);
ALTER TABLE RSP_POST          ADD CONSTRAINT C_RSP_POST_FK_P_POST           FOREIGN KEY (ID_POST_PARENT)    REFERENCES RSP_POST (ID_POST);
ALTER TABLE RSP_POST          ADD CONSTRAINT C_RSP_POST_FK_USUARIO          FOREIGN KEY (ID_USUARIO)        REFERENCES RSP_USUARIO (ID_USUARIO);
ALTER TABLE RSP_POST          ADD CONSTRAINT C_RSP_POST_FK_OG               FOREIGN KEY (ID_OPEN_GRAPH)     REFERENCES RSP_OPEN_GRAPH (ID_OPEN_GRAPH);
ALTER TABLE RSP_USUARIO_LOGIN ADD CONSTRAINT C_RSP_USUARIO_LOGIN_FK_USUARIO FOREIGN KEY (ID_USUARIO)        REFERENCES RSP_USUARIO (ID_USUARIO);
ALTER TABLE RSP_FOLLOW        ADD CONSTRAINT C_RSP_FOLLOW_FK_FOLLOWER       FOREIGN KEY (ID_FOLLOWER)       REFERENCES RSP_USUARIO (ID_USUARIO);
ALTER TABLE RSP_FOLLOW        ADD CONSTRAINT C_RSP_FOLLOW_FK_FOLLOWED       FOREIGN KEY (ID_FOLLOWED)       REFERENCES RSP_USUARIO (ID_USUARIO);
ALTER TABLE RSP_FOLLOW        ADD CONSTRAINT C_RSP_FOLLOW_FK_LIST           FOREIGN KEY (ID_LIST_FOLLOWED)  REFERENCES RSP_LIST (ID_LIST);
ALTER TABLE RSP_PROFILE_FIELD_VALUE ADD CONSTRAINT C_RSP_PROFILE_FIELD_VALUE_FK_USUARIO           FOREIGN KEY (ID_USUARIO)  REFERENCES RSP_USUARIO (ID_USUARIO);
ALTER TABLE RSP_PROFILE_FIELD_VALUE ADD CONSTRAINT C_RSP_PROFILE_FIELD_VALUE_FK_PROFILE_FIELD     FOREIGN KEY (ID_PROFILE_FIELD)  REFERENCES RSP_PROFILE_FIELD (ID_PROFILE_FIELD);

-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.USER_LIKE
-- -----------------------------------------------------
CREATE TABLE RSP_USER_LIKE (
  ID_USUARIO INTEGER NOT NULL REFERENCES RSP_USUARIO (ID_USUARIO),
  ID_POST INTEGER NOT NULL REFERENCES RSP_POST (ID_POST),
  DATE TIMESTAMP NOT NULL);






-- -----------------------------------------------------
-- TABLE RSP_SCHEMA.LIST_POST
-- -----------------------------------------------------
CREATE TABLE RSP_LIST_POST (
  ID_LIST INTEGER NOT NULL REFERENCES RSP_LIST (ID_LIST),
  ID_POST INTEGER NOT NULL REFERENCES RSP_POST (ID_POST)
);

CREATE SEQUENCE ID_RSP_IMAGE_SEQ;
CREATE SEQUENCE ID_RSP_USUARIO_SEQ;
CREATE SEQUENCE ID_OPEN_GRAPH_SEQ;
CREATE SEQUENCE ID_POST_SEQ;
CREATE SEQUENCE ID_LIST_SEQ;
CREATE SEQUENCE ID_FOLLOW_SEQ;



